modLoader = "javafml"
loaderVersion = "${neoforge_loader_version_range}"
license = "${mod_license}"

[[mods]]
modId = "potionsplus_shared"
version = "${mod_version}"
displayName = "Coo Core"
authors = "${mod_authors}"
credits = "${credits}"
description = '''
Core library providing common utilities and base functionality for modular Minecraft mods.
This mod is required by both Potions Plus and Simple Skills.
'''

[[dependencies.potionsplus_shared]]
modId = "neoforge"
type = "required"
versionRange = "${neo_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.potionsplus_shared]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"