package grill24.potionsplus.core.blocks;

import net.minecraft.core.Holder;
import net.minecraft.world.level.block.Block;

import java.util.List;

public class FlowerBlocks {
    public static Holder<Block> TOMATO_PLANT;
    public static Holder<Block> BRASSICA_OLERACEA_PLANT, CABBAGE_PLANT, KALE_PLANT, BROCCOLLI_PLANT, CAULIFLOWER_PLANT, BRUSSELS_SPROUTS_PLANT, KOHLRABI_PLANT;
    public static Holder<Block> TALL_GRASS_VERSATILE, LARGE_FERN_VERSATILE;
    public static List<Holder<Block>> GENETIC_CROP_PLANTS;

    // Worldgen plants
    public static Holder<Block> SURVIVOR_STICK, COWLICK_VINE, HANGING_FERN, DROOPY_VINE, LUMOSEED_SACKS, LUNAR_BERRY_BUSH;

    // Versatile vanilla flowers
    public static Holder<Block> DANDELION_VERSATILE, TORCHFLOWER_VERSATILE, POPPY_VERSATILE, BLUE_ORCHID_VERSATILE, ALLIUM_VERSATILE, AZURE_BLUET_VERSATILE, RED_TULIP_VERSATILE, ORANGE_TULIP_VERSATILE, WHITE_TULIP_VERSATILE, PINK_TULIP_VERSATILE, OXEYE_DAISY_VERSATILE, CORNFLOWER_VERSATILE, WITHER_ROSE_VERSATILE, LILY_OF_THE_VALLEY_VERSATILE, BROWN_MUSHROOM_VERSATILE, RED_MUSHROOM_VERSATILE;
    public static Holder<Block> SUNFLOWER_VERSATILE, LILAC_VERSATILE, ROSE_BUSH_VERSATILE, PEONY_VERSATILE, PITCHER_PLANT_VERSATILE;
}
